name: GITHUB CI --> Bot dev_sentinel by Lucas Moran

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bot-snake-main

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar versiones de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'bot-snake-main/requirements.txt'

    - name: Instalar dependencias del proyecto
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest flake8 pytest-cov coverage

    - name: Verificación de sintaxis (Linter)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Probar importación del Engine
      run: |
        PYTHONPATH=./BOT/dev_sentinel python -c "import BOT.dev_sentinel.game_engine; print('Engine cargado correctamente')"

    - name: Simulación de partida con reporte de Cobertura
      run: |
        if [ -f "run_local_match_with_bot.py" ]; then
          PYTHONPATH=./BOT/dev_sentinel coverage run --source=BOT/dev_sentinel run_local_match_with_bot.py
          coverage report -m --omit="**/pygame.py,**/ws_client.py,**/main.py,**/client_runner.py"
        fi
        
    - name: Simulación de partida y Tests Unitarios
      run: |
        if [ -f "run_local_match_with_bot.py" ]; then
          # 1. Simulación en vivo
          PYTHONPATH=./BOT/dev_sentinel coverage run --source=BOT/dev_sentinel run_local_match_with_bot.py
          
          # 2. Test unitario de las 7 líneas faltantes (-a acumula la cobertura)
          PYTHONPATH=.:./BOT/dev_sentinel:./BOT/dev_sentinel/tests coverage run -a --source=BOT/dev_sentinel -m unittest test_game_engine.py
          # 3. Reporte final
          coverage report -m --omit="**/pygame.py,**/ws_client.py,**/main.py,**/client_runner.py"
        fi
      